### ISSUE TITLE
Loader not going away

### ISSUE THREAD

**Issue by nitin-1926** [fnplus/fnplus.github.io#8]
On the contact us page, behind the contact google form, there is a loader which is still there when the google form is loaded
![Screenshot (88)](https://user-images.githubusercontent.com/44253685/91696871-daae6600-eb8d-11ea-9a2d-3bfe3735775b.png)
![Screenshot (89)](https://user-images.githubusercontent.com/44253685/91696890-e13cdd80-eb8d-11ea-9eaa-4a9a135eb247.png)
![Screenshot (90)](https://user-images.githubusercontent.com/44253685/91696893-e1d57400-eb8d-11ea-9ad0-ec151c19bc46.png)

**Comment by nitin-1926** [comment]
Can I take up this issue?

**Comment by xlogix** [comment]
Yes you can!

**Comment by nitin-1926** [comment]
On it.
