### ISSUE TITLE
Wrong Format of Birthdate

### ISSUE THREAD

**Issue by Siddhant-K-code** [fnplus/fnplus.github.io#9]
![image](https://user-images.githubusercontent.com/55068936/98208270-07eb0c00-1f63-11eb-8582-dfe77757eb31.png)
In `https://airtable.com/shrvcsx9Prqt12z6e`

In the Birthday Section, an Example is given in `dd/mm/yyyy`
but in Column it is `mm/dd/yyyy`

**Comment by xlogix** [comment]
Thanks for letting me know. I'll update the same

**Comment by xlogix** [comment]
Fixed!
